# Generated by Django 2.1.2 on 2018-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181105_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicmanager',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.jpg', null=True, upload_to='profilePic/'),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.jpg', null=True, upload_to='profilePic/'),
        ),
        migrations.AlterField(
            model_name='hospitalauthority',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.jpg', null=True, upload_to='profilePic/'),
        ),
        migrations.AlterField(
            model_name='warehousepersonnel',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.jpg', null=True, upload_to='profilePic/'),
        ),
    ]
