# Generated by Django 2.1.2 on 2018-11-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181105_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcatalogue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
