# Generated by Django 2.1.2 on 2018-11-16 19:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181116_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=main.models.Token.id_generator, editable=False, max_length=10),
        ),
    ]
