# Generated by Django 2.1.2 on 2018-11-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181117_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmanager',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.png', null=True, upload_to='profilePic/'),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.png', null=True, upload_to='profilePic/'),
        ),
        migrations.AddField(
            model_name='hospitalauthority',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.png', null=True, upload_to='profilePic/'),
        ),
        migrations.AddField(
            model_name='warehousepersonnel',
            name='image',
            field=models.ImageField(blank=True, default='profilePic/noUserPic.png', null=True, upload_to='profilePic/'),
        ),
    ]
