# Generated by Django 2.1.2 on 2018-11-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181117_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='role',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
